// Login
// {
//    "displayName":null,
//    "email":"vavoli3014@migonom.com",
//    "emailVerified":false,
//    "isAnonymous":false,
//    "metadata":{
//       "creationTime":1664475243711,
//       "lastSignInTime":1664475327549
//    },
//    "phoneNumber":null,
//    "photoURL":null,
//    "providerData":[
//       [
//          "Object"
//       ]
//    ],
//    "providerId":"firebase",
//    "tenantId":null,
//    "uid":"pptaCUJdI0HncumbaWxsN0H8sHsn"
// }